version: '3.1'

services:
  zinc-server:
    build: ./zinc-server
    ports:
      - "6001:4080"

  e-lookup-be:
    build: ./e-lookup-be
    ports:
      - "6002:3000"
    environment:
      ZINC_SERVER_HOST: http://zinc-server:4080/
    depends_on:
      - zinc-server

  e-lookup-fe:
    build:
      context: ./e-lookup-fe
      args:
        elookupbe_host: ${ELOOKUPBE_REMOTE_HOST:-http://localhost:6002/}
    ports:
      - "6003:3000"
    depends_on:
      - e-lookup-be
